[package]
name = "m3u8parse"
version = "0.1.0"
edition = "2021"
author = "Michael Mileusnich <michael.mileusnich@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }